jump-dev/HiGHS.jl

- README.md
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Based on a slimmed down version of the GLPK wrapper, so it took me much less time than expected.
There are still a few outstanding TODO items, including one serious segfault in
linear 8b. (_Edit: confirmed as segfault in HiGHS and reported upstream: https://github.com/ERGO-Code/HiGHS/issues/448_)
The HiGHS API has a few quirks (links to tracking upstream issues).
- It is very talky (https://github.com/ERGO-Code/HiGHS/issues/446, https://github.com/ERGO-Code/HiGHS/issues/358)
- There is no way to get the error message from a return code (https://github.com/ERGO-Code/HiGHS/issues/449)
- The duality convention for rows is different from columns by a factor of -1.
- There is no way to change constraint coefficients (https://github.com/ERGO-Code/HiGHS/issues/449)
- There is no way to get the …
> Do a full rewrite of the MOI wrapper.

- README.md
@jajhall, HiGHS.jl is [now a registered package in Julia](https://github.com/JuliaRegistries/General/pull/29660) and available by anyone to use with automated installs on Windows, Mac, and Linux!
> [README] Update now that HiGHS is registered

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Currently WIP (tests failing) because HiGHS doesn't seem to be able to reliably find rays. It get warnings like:
```
INFO   : Problem status detected on presolve: Unbounded
WARNING: Method getPrimalRay is still under development and behaviour may be unpredictable
```
Closes #26
> Add support for infeasibility certificates

- README.md
some option names have changed so I copy-pasted https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.set which seemed to be the source of the original options descriptor. 
FWIW the change of `mip_epsilon` to `mip_feasibility_tolerance` is what triggered the change.
> Update options list

- Project.toml
- gen/Project.toml
- gen/gen.jl
- gen/generate.toml
- src/HiGHS.jl
- src/MOI_wrapper.jl
- src/gen/libhighs.jl
- src/gen/libhighs_common.jl
- test/MOI_wrapper.jl
Closes https://github.com/jump-dev/HiGHS.jl/issues/70
Closes https://github.com/jump-dev/HiGHS.jl/issues/73
Closes https://github.com/jump-dev/HiGHS.jl/issues/80
> Update to HiGHS v1.2.0

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
A terrible, horrible, no good, very bad way of setting the QP objective function: get/set the entire problem!
This is just a placeholder to check for obvious QP bugs before we get support for setting the hessian without `passModel`.
> Add QP solver

- src/MOI_wrapper.jl
> Add support for NumberOfThreads

- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Fix SimplexIterations getter and add BarrierIterations

- Project.toml
- gen/Project.toml
- gen/gen.jl
- gen/generate.toml
- src/HiGHS.jl
- src/MOI_wrapper.jl
- src/gen/libhighs.jl
- test/C_wrapper.jl
Lots of great changes here. Now with exported C constants and docstrings!
> Update to HiGHS v1.2.1

- src/MOI_wrapper.jl
Closes #97 
The example in #97 now returns:
```julia
julia> solution_summary(model)
* Solver : HiGHS
* Status
Termination status : OPTIMAL
Primal status      : INFEASIBLE_POINT
Dual status        : INFEASIBLE_POINT
Message from the solver:
"7"
* Candidate solution
Objective value      : 144677.302624058
Objective bound      : 0.0
Dual objective value : 180188.05708437136
* Work counters
Solve time (sec)   : 0.12055
Simplex iterations : 488
Barrier iterations : 0
```
Not adding it as a test because it's really an upstream bug in HiGHS that will get fixed at some point.
> Fix INFEASIBLE_POINT statuses

- src/MOI_wrapper.jl
Closes #105
@grahamgill do you have an example of a model that generates a warning in `Highs_run` so we can test this?
> Fix termination status when Highs_run warns

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add better error message for bad options

- README.md
Modified the `dual_steepest_edge_weight_log_error_threshol`, `dual_simpl…ex_cost_perturbation_multiplie`, and `primal_simplex_bound_perturbation_multiplier` values to double instead of Int (by simply inserting decimal points), since that's the required type and `solution_file`, `log_file`, and `write_model_file` values to string type `("")` instead of blank. Otherwise, these give rise to errors while executing the HiGHS solver from JuMP.
> Fixed the README settings parameter datatype with more clarity, which can otherwise be misleading especially to beginners.

- Project.toml
- src/HiGHS.jl
This pull request migrates the package from [SnoopPrecompile](https://github.com/timholy/SnoopCompile.jl/tree/master/SnoopPrecompile) to [PrecompileTools](https://github.com/JuliaLang/PrecompileTools.jl).
PrecompileTools is **nearly a drop-in replacement** except that there are **changes in naming and how developers locally disable precompilation** (to make their development workflow more efficient). These changes are described in [PrecompileTool's enhanced documentation](https://julialang.github.io/PrecompileTools.jl/stable/), which also includes instructions for users on how to set up custom "Startup" packages, handling precompilation tasks that are not amenable to workloads, and tips for troubleshooting.
Why the new package? It meets several goals:
- The name "SnoopPrecompile" was …
> Migrate from SnoopPrecompile to PrecompileTools

- test/MOI_wrapper.jl
This failed a recent run of `solver-tests.yml` in MOI. It's a bit strict regardless, so let's loosen.
> Relax tolerance of test_RelativeGap

- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes #172 
This took me a while to find because...GLPK has the exact same bug. So I originally figured that two solvers meant the problem was in MOI.
> Fix copy_to with empty constraint rows

- Project.toml
@matbesancon we forgot to bump the compat bound when adding #177. This broke tests for a user of HiGHS.jl.
> Fix compat for ObjectiveLimit

- src/MOI_wrapper.jl
> Fix zeroAllClocks usage in earlier versions

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
https://github.com/jump-dev/MathOptInterface.jl/pull/2318 is exposing all the bugs.
> Fix deleting ZeroOne constraints after MOI.optimize

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
It seems that we can pass `numnz=0` to empty the Hessian and clear quadratic objective.
> Optimize the approach to clear quadratic objective

- Project.toml
- gen/Project.toml
- src/gen/libhighs.jl
Closes #204 
Diff: https://github.com/ERGO-Code/HiGHS/compare/v1.6.0...v1.7.0#diff-b3541c8287e02b52ca82b336943540cbbff052ee623f60c9d8ed9f90c95fcfbe
There are a few new methods
> Support HiGHS v1.7.0

- src/HiGHS.jl
I'm playing around with static compilation. This seemed easy enough to fix, to avoid:
```
Dynamic call to Base.convert(Type, String)
In C:\Users\visser_mn\.julia\packages\HiGHS\MQAyL\src\HiGHS.jl:13
```
> Remove unneeded __init__ function

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
This avoids the expensive #207 in the get-fallback.
Closes #225
> Use HiGHS to compute the dual objective value

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Fix ObjectiveBound and RelativeGap for LP models

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add CallbackFunction to MOI wrapper

- src/MOI_wrapper.jl
> Fix performance of DualObjectiveValue when a ray is present

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
The dual ray could have the incorrect sign (by tolerance), which would result in the wrong bound being multiplied if only one side is finite.
Closes #236
> Fix DualObjectiveValue

- src/MOI_wrapper.jl
> Add support for MOI.add_constrained_variable

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
We call `_info` a lot. The previous code did a hash lookup twice. Once to checkin the key existed (the most common case), and then once to get the actual value. This simplifies the code to a single hash lookup.
> Improve performance of haskey lookups

- Project.toml
- src/HiGHS.jl
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add support for two-set add_constrained_variable

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Fix dual objective value with free variable

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add support for ObjectiveFunction{VectorAffineFunction}

- test/MOI_wrapper.jl
These shouldn't be needed because the methods are actually hit. But coverage doesn't see them for some reason.
> Improve test coverage

- README.md
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add HiGHS.ComputeInfeasibilityCertificate attribute

- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Alternative to https://github.com/jump-dev/HiGHS.jl/pull/272
I think earlier versions of HiGHS either didn't support names, or they were quite slow. It looks like this was fixed in v1.7.1: https://github.com/ERGO-Code/HiGHS/pull/1782
> Pass names to the solver in HiGHS.Optimizer

- src/gen/libhighs.jl
I should have noticed that https://github.com/jump-dev/HiGHS.jl/pull/281 didn't rebuild the correct commit.
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/11370#issuecomment-2953183337, https://github.com/JuliaPackaging/Yggdrasil/pull/11378
> Fix gen/libhighs.jl to point to the latest commit

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes https://github.com/jump-dev/HiGHS.jl/issues/291
This is a temporary hack. It doesn't really address the issue. I need to investigate more.
> Disable kHighsCallbackSimplexInterrupt in default callback
