jump-dev/HiGHS.jl

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
This is as far as I got before being blocked by https://github.com/ERGO-Code/HiGHS/issues/223.
Should we move this repo to JuMP-dev for easier collaboration?
> test SolverName and implement is_empty

- src/HiGHS.jl
- src/MOI_wrapper.jl
- src/options.jl
- src/wrapper/api_helpers.jl
- test/MOI_wrapper.jl
with https://github.com/ERGO-Code/HiGHS/issues/223 closed, we can add options. Not all of them are implemented yet, not sure what are their stability
> Added options

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Refactoring tests in test sets, handling feasibility sense correctly, adding objective function
> Objective function

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
I'm mostly a user of math opt, and don't have a terribly deep understanding. If it appears I am missing something obvious, I probably am.
> Here is a stab at a terminations status

- test/C_wrapper.jl
- test/MOI_wrapper.jl
- test/runtests.jl
This PR just refactors the tests in anticipation of some incoming MOI changes.
> Refactor tests

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add support for MOI.ConstraintBasisStatus

- Project.toml
- src/MOI_wrapper.jl
- src/wrapper/libhighs_api.jl
- test/MOI_wrapper.jl
Three separate commits. I'll merge without squashing, but it was easier to do it this way rather than PR, wait, PR, PR.
Closes #27
> Update to HiGHS_jll 0.2.1

- src/MOI_wrapper.jl
See https://github.com/ERGO-Code/HiGHS/issues/468#issuecomment-781422574
Now that I hooked the basis information up, we can use that. I'm not entirely convinced that it is worth it, because the dual could previously be wrong by at most the dual feasibility tolerance.
> Use basis status to get dual info

- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add fast copy_to

- Project.toml
- src/wrapper/libhighs_api.jl
- test/MOI_wrapper.jl
Closes #44 
Closes #43 
Closes #36
> Bump HiGHS_jll and refactor tests

- src/MOI_wrapper.jl
> Handle errors from Highs_run

- .gitignore
- Project.toml
- gen/gen.jl
- src/HiGHS.jl
- src/MOI_wrapper.jl
- src/gen/libhighs_api.jl
- src/gen/libhighs_common.jl
- test/C_wrapper.jl
- test/MOI_wrapper.jl
- test/runtests.jl
cc @galabovaa 
Closes #30 
Next step after this is MIP and QP support. But they can be separate PRs.
> Bump to the new release of HiGHS_jll

- Project.toml
- src/MOI_wrapper.jl
- src/gen/libhighs_api.jl
- src/gen/libhighs_common.jl
- test/MOI_wrapper.jl
Quite a few failures. Not sure if bugs in HiGHS or my wrapper. Opening CI to see how it gets on.
> Add MIP solver to HiGHS

- Project.toml
- src/MOI_wrapper.jl
- src/gen/libhighs_api.jl
- src/gen/libhighs_common.jl
- test/C_wrapper.jl
- test/MOI_wrapper.jl
This is a mix of a few changes. I haven't managed to track down the bug in the MIP solver. But throwing away the inner `Ptr` and getting a new one was sufficient. It seems like `Highs_clearModel` doesn't completely clear the integrality stuff?
Closes #55
> Bump HiGHS_jll and fix bugs in MIP solver

- README.md
> Add options to README

- src/MOI_wrapper.jl
@SupplyChef can you try this branch out?
```
] add HiGHS#od/fix-copy-to
```
> Fix MOI.copy_to

- Project.toml
- src/MOI_wrapper.jl
> Update to HiGHS v1.1

- src/MOI_wrapper.jl
This will be tested in the next release of MOI.
> Fix solutions for infeasibility certificates

- Project.toml
- README.md
This also increments the minimum Julia version to the LTS, and provides native binaries for M1.
> Bump to HiGHS v1.1.1

- README.md
HiGHS is now at a point where I feel safe recommending it. We shouldn't scare users away with this warning.
> Remove warning from the README

- Project.toml
x-ref: https://github.com/jump-dev/JuMP.jl/issues/2564
> Update to MOI v1.0

- Project.toml
- src/MOI_wrapper.jl
> Fix output of RawStatusString

- src/MOI_wrapper.jl
> Fix missing == in asserts

- LICENSE
- gen/gen.jl
- src/HiGHS.jl
- src/MOI_wrapper.jl
- src/gen/libhighs.jl
- test/C_wrapper.jl
- test/MOI_wrapper.jl
- test/runtests.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/1813
> Add license headers

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes https://github.com/jump-dev/MathOptInterface.jl/issues/2027
> Fix adding variable and constraint names in copy_to

- Project.toml
> Update to HiGHS_jll@1.4.0

- src/MOI_wrapper.jl
Closes #126
This won't work for now, because it requires a new upstream release of HiGHS.
> Add support for VariablePrimalStart

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add Semicontinuous and Semiinteger support

- Project.toml
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/5954
> Add support for HiGHS v1.4.1

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Raised on discourse: https://discourse.julialang.org/t/jump-delete-is-slower-than-building-a-new-model/92597
> Fix performance of deleting multiple linear constraints

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes https://github.com/jump-dev/HiGHS.jl/issues/145
> Detail expected value type in RawOptimizerAttribute error

- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes #148 
We obviously need to add tests to MOI for this.
> Fix bug when setting a quadratic objective

- Project.toml
x-ref: https://github.com/ERGO-Code/HiGHS/releases/tag/v1.4.2
> Add support for upstream v1.4.2

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Fix duals in a QP

- src/MOI_wrapper.jl
Closes #160 
Users can still over-ride this manually.
> Set Threads on Windows by default

- Project.toml
> Prep for v1.5.2

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2256
> Fix support for MOI.TimeLimitSec

- Project.toml
- src/MOI_wrapper.jl
adds the absolute and relative gap limit attributes to HiGHS.
> Add support for MOI.AbsoluteGapTolerance and MOI.RelativeGapTolerance

- Project.toml
- gen/Project.toml
- src/MOI_wrapper.jl
- src/gen/libhighs.jl
> Add support for v1.6.0

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes #193 
@joaquim constraint RHS as well?
> Add support for vector-valued MOI.set when setting new ConstraintSet

- test/MOI_wrapper.jl
> Add test for writing mps.gz files

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
I don't think it was ever possible to hit the `INFEASIBLE_POINT` status before this PR.
> Fix getting infeasible primal/dual solutions

- Project.toml
- src/gen/libhighs.jl
I probably need to rebuild the C API.
> Update to HiGHS_jll@1.8.0

- README.md
Someone was confused and thought these were necessary.
> Update README.md to clarify options are optional

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes #241 
I didn't test locally, so let's see what the impact is.
> Fix supports_constraint(::Optimizer, ::Type{VariableIndex}, ::Type{ZeroOne})

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
x-ref https://github.com/jump-dev/JuMP.jl/issues/3948
> Add support for MOI.write_to_file

- Project.toml
- src/MOI_wrapper.jl
- src/gen/libhighs.jl
I need to think about the right way to support different versions of upstream HiGHS.
One option is to just keep a single fixed version of upstream with HiGHS.jl. The other is to allow multiple versions and then do something like Gurobi.jl where we dynamically load the right header.
> Update to HiGHS_jll@1.11.0

- README.md
> Add a citation to the README.md

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Fix issue 287
